import os
env=SConscript('SConscript')


# Walk through directories "libraries", "components" and "applications"
for curBaseDir in env.dirList('.', 'libraries'):
  SConscript(dirs=curBaseDir, exports=['env','curBaseDir'], variant_dir = os.path.join(env['PEFBUILD'], curBaseDir), duplicate = False)

for curBaseDir in env.dirList('.', 'components'):
  SConscript(dirs=curBaseDir, exports=['env','curBaseDir'], variant_dir = os.path.join(env['PEFBUILD'], curBaseDir), duplicate = False)

for curBaseDir in env.dirList('.', 'applications'):
  SConscript(dirs=curBaseDir, exports=['env','curBaseDir'], variant_dir = os.path.join(env['PEFBUILD'], curBaseDir), duplicate = False)

#doxygen and graphviz needs to be present!
if env['PEFCONFIG']['pefDoxygen'] == True:
  resourceDir=os.path.join(env['PEFBASE'], "..", "resources")
  env2=env.Clone(tools = ["doxygen"], toolpath = [resourceDir])  
  docroot=os.path.join(env['PEFBASE'],'..','..','..','doc')

  pefDoc = env2.Doxygen(os.path.join(env['PEFBASE'], "..", "resources", "pef.doxyfile"))
  #pefPDF = env2.PDF(docroot + '/pef.pdf', os.path.join(docroot, 'latex','refman.tex'))
  #Depends(pefPDF, env.dirList(".", os.path.join(docroot, 'latex')))
  cleaningList=env.dirList(".", docroot, True)
  Clean(pefDoc, cleaningList)
  Alias('doc', [pefDoc])

