# libraries/logger/SConscript
import os
Import('env','curBaseDir')

logfiles = env.checkLogger(curBaseDir)

loggerStatic = env.StaticLibrary('logger.c', CCFLAGS=env['CCFLAGS']+'-fno-builtin -O2 -fPIC ')
env.Append(ESF_logger = loggerStatic)

Alias('logger', loggerStatic)
