/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Services_CONSTANTS_H
#define Services_CONSTANTS_H

#include "Services_types.h"

namespace de { namespace tum { namespace in { namespace i22 { namespace uc { namespace thrift { namespace types {

class ServicesConstants {
 public:
  ServicesConstants();

};

extern const ServicesConstants g_Services_constants;

}}}}}}} // namespace

#endif
