/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Services_constants.h"

namespace de { namespace tum { namespace in { namespace i22 { namespace uc { namespace thrift { namespace types {

const ServicesConstants g_Services_constants;

ServicesConstants::ServicesConstants() {
}

}}}}}}} // namespace

