/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Types_constants.h"

namespace de { namespace tum { namespace in { namespace i22 { namespace uc { namespace thrift { namespace types {

const TypesConstants g_Types_constants;

TypesConstants::TypesConstants() {
}

}}}}}}} // namespace

