/*
 * ucDeclass.c
 *
 *  Created on: Jul 1, 2013
 *      Author: user
 */


#include "ucDeclass.h"

GHashTable *processes;

gint intCmp(gconstpointer a, gconstpointer b, gpointer user_data) {
	// should sort in reverse order
	struct timeval *ta = a;
	struct timeval *tb = b;

	return ((ta->tv_sec != tb->tv_sec)
			? (tb->tv_sec - ta->tv_sec)
			: (tb->tv_usec - ta->tv_usec));
}


void ucDeclassEvent(pid_t pid, char scno) {
	struct declass *decl = calloc(1, sizeof(struct declass));

	decl->pid = pid;
	decl->syscallno = scno;
	gettimeofday(&decl->time, NULL);
}


void ucDeclass__init() {
	processes = g_hash_table_new_full(g_int_hash, g_int_equal, free, g_tree_destroy);
}

void ucDeclass_add(pid_t pid, ucDataSet dataSet) {
	GTree *times;
	pid_t *pidCopy;

	if (!(times = g_hash_table_lookup(processes, &pid))) {
		if (!(pidCopy = calloc(1, sizeof(pid_t)))) {
			ucDeclass_errorExit("Unable to allocate enough memory");
		}
		*pidCopy = pid;
		times = g_tree_new_full(intCmp, NULL, free, g_hash_table_destroy);

		g_hash_table_insert(processes, pidCopy, times);
	}


}


extern int ucDeclassEvents[] = {
	[SYS_accept] = 0,
	[SYS_access] = 0,
	[SYS_acct] = 0,
	[SYS_add_key] = 0,
	[SYS_adjtimex] = 0,
	[SYS_afs_syscall] = 0,
	[SYS_alarm] = 0,
	[SYS_bdflush] = 0,
	[SYS_bind] = 0,
	[SYS_break] = 0,
	[SYS_brk] = 0,
	[SYS_capget] = 0,
	[SYS_capset] = 0,
	[SYS_chdir] = 0,
	[SYS_chmod] = 0,
	[SYS_chown32] = 0,
	[SYS_chown] = 0,
	[SYS_chroot] = 0,
	[SYS_clock_adjtime] = 0,
	[SYS_clock_getres] = 0,
	[SYS_clock_gettime] = 0,
	[SYS_clock_nanosleep] = 0,
	[SYS_clock_settime] = 0,
	[SYS_clone] = 0,
	[SYS_close] = 0,
	[SYS_connect] = 0,
	[SYS_create_module] = 0,
	[SYS_creat] = 0,
	[SYS_delete_module] = 0,
	[SYS_dup2] = 0,
	[SYS_dup3] = 0,
	[SYS_dup] = 0,
	[SYS_epoll_create1] = 0,
	[SYS_epoll_create] = 0,
	[SYS_epoll_ctl] = 0,
	[SYS_epoll_pwait] = 0,
	[SYS_epoll_wait] = 0,
	[SYS_eventfd2] = 0,
	[SYS_eventfd] = 0,
	[SYS_execve] = 0,
	[SYS_exit_group] = 0,
	[SYS_exit] = 0,
	[SYS_faccessat] = 0,
	[SYS_fadvise64_64] = 0,
	[SYS_fadvise64] = 0,
	[SYS_fallocate] = 0,
	[SYS_fanotify_init] = 0,
	[SYS_fanotify_mark] = 0,
	[SYS_fchdir] = 0,
	[SYS_fchmodat] = 0,
	[SYS_fchmod] = 0,
	[SYS_fchown32] = 0,
	[SYS_fchownat] = 0,
	[SYS_fchown] = 0,
	[SYS_fcntl64] = 0,
	[SYS_fcntl] = 0,
	[SYS_fdatasync] = 0,
	[SYS_fgetxattr] = 0,
	[SYS_flistxattr] = 0,
	[SYS_flock] = 0,
	[SYS_fork] = 0,
	[SYS_fremovexattr] = 0,
	[SYS_fsetxattr] = 0,
	[SYS_fstat64] = 0,
	[SYS_fstatat64] = 0,
	[SYS_fstatfs64] = 0,
	[SYS_fstatfs] = 0,
	[SYS_fstat] = 0,
	[SYS_fsync] = 0,
	[SYS_ftime] = 0,
	[SYS_ftruncate64] = 0,
	[SYS_ftruncate] = 0,
	[SYS_futex] = 0,
	[SYS_futimesat] = 0,
	[SYS_getcpu] = 0,
	[SYS_getcwd] = 0,
	[SYS_getdents64] = 0,
	[SYS_getdents] = 0,
	[SYS_getegid32] = 0,
	[SYS_getegid] = 0,
	[SYS_geteuid32] = 0,
	[SYS_geteuid] = 0,
	[SYS_getgid32] = 0,
	[SYS_getgid] = 0,
	[SYS_getgroups32] = 0,
	[SYS_getgroups] = 0,
	[SYS_getitimer] = 0,
	[SYS_get_kernel_syms] = 0,
	[SYS_get_mempolicy] = 0,
	[SYS_getpeername] = 0,
	[SYS_getpgid] = 0,
	[SYS_getpgrp] = 0,
	[SYS_getpid] = 0,
	[SYS_getpmsg] = 0,
	[SYS_getppid] = 0,
	[SYS_getpriority] = 0,
	[SYS_getresgid32] = 0,
	[SYS_getresgid] = 0,
	[SYS_getresuid32] = 0,
	[SYS_getresuid] = 0,
	[SYS_getrlimit] = 0,
	[SYS_get_robust_list] = 0,
	[SYS_getrusage] = 0,
	[SYS_getsid] = 0,
	[SYS_getsockname] = 0,
	[SYS_getsockopt] = 0,
	[SYS_get_thread_area] = 0,
	[SYS_gettid] = 0,
	[SYS_gettimeofday] = 0,
	[SYS_getuid32] = 0,
	[SYS_getuid] = 0,
	[SYS_getxattr] = 0,
	[SYS_gtty] = 0,
	[SYS_idle] = 0,
	[SYS_init_module] = 0,
	[SYS_inotify_add_watch] = 0,
	[SYS_inotify_init1] = 0,
	[SYS_inotify_init] = 0,
	[SYS_inotify_rm_watch] = 0,
	[SYS_io_cancel] = 0,
	[SYS_ioctl] = 0,
	[SYS_io_destroy] = 0,
	[SYS_io_getevents] = 0,
	[SYS_ioperm] = 0,
	[SYS_iopl] = 0,
	[SYS_ioprio_get] = 0,
	[SYS_ioprio_set] = 0,
	[SYS_io_setup] = 0,
	[SYS_io_submit] = 0,
	[SYS_ipc] = 0,
	[SYS_kexec_load] = 0,
	[SYS_keyctl] = 0,
	[SYS_kill] = 0,
	[SYS_lchown32] = 0,
	[SYS_lchown] = 0,
	[SYS_lgetxattr] = 0,
	[SYS_linkat] = 0,
	[SYS_link] = 0,
	[SYS_listen] = 0,
	[SYS_listxattr] = 0,
	[SYS_llistxattr] = 0,
	[SYS__llseek] = 0,
	[SYS__llseek] = 0,
	[SYS_lock] = 0,
	[SYS_lookup_dcookie] = 0,
	[SYS_lremovexattr] = 0,
	[SYS_lseek] = 0,
	[SYS_lsetxattr] = 0,
	[SYS_lstat64] = 0,
	[SYS_lstat] = 0,
	[SYS_madvise] = 0,
	[SYS_mbind] = 0,
	[SYS_migrate_pages] = 0,
	[SYS_mincore] = 0,
	[SYS_mkdirat] = 0,
	[SYS_mkdir] = 0,
	[SYS_mknodat] = 0,
	[SYS_mknod] = 0,
	[SYS_mlockall] = 0,
	[SYS_mlock] = 0,
	[SYS_mmap2] = 0,
	[SYS_mmap] = 0,
	[SYS_modify_ldt] = 0,
	[SYS_mount] = 0,
	[SYS_move_pages] = 0,
	[SYS_mprotect] = 0,
	[SYS_mpx] = 0,
	[SYS_mq_getsetattr] = 0,
	[SYS_mq_notify] = 0,
	[SYS_mq_open ] = 0,
	[SYS_mq_timedreceive] = 0,
	[SYS_mq_timedsend] = 0,
	[SYS_mq_unlink] = 0,
	[SYS_mremap] = 0,
	[SYS_msync] = 0,
	[SYS_munlockall] = 0,
	[SYS_munlock] = 0,
	[SYS_munmap] = 0,
	[SYS_name_to_handle_at] = 0,
	[SYS_nanosleep] = 0,
	[SYS__newselect] = 0,
	[SYS_nfsservctl] = 0,
	[SYS_nice] = 0,
	[SYS_oldfstat] = 0,
	[SYS_oldlstat] = 0,
	[SYS_oldolduname] = 0,
	[SYS_oldstat] = 0,
	[SYS_olduname] = 0,
	[SYS_openat] = 0,
	[SYS_open_by_handle_at] = 0,
	[SYS_open] = 0,
	[SYS_pause] = 0,
	[SYS_perf_event_open] = 0,
	[SYS_personality] = 0,
	[SYS_pipe2] = 0,
	[SYS_pipe] = 0,
	[SYS_pivot_root] = 0,
	[SYS_poll] = 0,
	[SYS_ppoll] = 0,
	[SYS_prctl] = 0,
	[SYS_pread64] = 0,
	[SYS_preadv] = 0,
	[SYS_prlimit64] = 0,
	[SYS_process_vm_readv] = 0,
	[SYS_process_vm_writev] = 0,
	[SYS_profil] = 0,
	[SYS_prof] = 0,
	[SYS_pselect6] = 0,
	[SYS_ptrace] = 0,
	[SYS_putpmsg] = 0,
	[SYS_pwrite64] = 0,
	[SYS_pwritev] = 0,
	[SYS_query_module] = 0,
	[SYS_quotactl] = 0,
	[SYS_readahead] = 0,
	[SYS_readdir] = 0,
	[SYS_readlinkat] = 0,
	[SYS_readlink] = 0,
	[SYS_read] = 0,
	[SYS_readv] = 0,
	[SYS_reboot] = 0,
	[SYS_recvfrom] = 0,
	[SYS_recvmmsg] = 0,
	[SYS_recvmsg] = 0,
	[SYS_recv] = 0,
	[SYS_remap_file_pages] = 0,
	[SYS_removexattr] = 0,
	[SYS_renameat] = 0,
	[SYS_rename] = 0,
	[SYS_request_key] = 0,
	[SYS_restart_syscall] = 0,
	[SYS_rmdir] = 0,
	[SYS_rt_sigaction] = 0,
	[SYS_rt_sigaction] = 0,
	[SYS_rt_sigpending] = 0,
	[SYS_rt_sigprocmask] = 0,
	[SYS_rt_sigqueueinfo] = 0,
	[SYS_rt_sigreturn] = 0,
	[SYS_rt_sigsuspend] = 0,
	[SYS_rt_sigtimedwait] = 0,
	[SYS_rt_tgsigqueueinfo] = 0,
	[SYS_sched_getaffinity] = 0,
	[SYS_sched_getparam] = 0,
	[SYS_sched_get_priority_max] = 0,
	[SYS_sched_get_priority_min] = 0,
	[SYS_sched_getscheduler] = 0,
	[SYS_sched_rr_get_interval] = 0,
	[SYS_sched_setaffinity] = 0,
	[SYS_sched_setparam] = 0,
	[SYS_sched_setscheduler] = 0,
	[SYS_sched_yield] = 0,
	[SYS_select] = 0,
	[SYS_sendfile64] = 0,
	[SYS_sendfile] = 0,
	[SYS_sendmmsg] = 0,
	[SYS_sendmsg] = 0,
	[SYS_send] = 0,
	[SYS_sendto] = 0,
	[SYS_setdomainname] = 0,
	[SYS_setfsgid32] = 0,
	[SYS_setfsgid] = 0,
	[SYS_setfsuid32] = 0,
	[SYS_setfsuid] = 0,
	[SYS_setgid32] = 0,
	[SYS_setgid] = 0,
	[SYS_setgroups32] = 0,
	[SYS_setgroups] = 0,
	[SYS_sethostname] = 0,
	[SYS_setitimer] = 0,
	[SYS_set_mempolicy] = 0,
	[SYS_setns] = 0,
	[SYS_setpgid] = 0,
	[SYS_setpriority] = 0,
	[SYS_setregid32] = 0,
	[SYS_setregid] = 0,
	[SYS_setresgid32] = 0,
	[SYS_setresgid] = 0,
	[SYS_setresuid32] = 0,
	[SYS_setresuid] = 0,
	[SYS_setreuid32] = 0,
	[SYS_setreuid] = 0,
	[SYS_setrlimit] = 0,
	[SYS_set_robust_list] = 0,
	[SYS_setsid] = 0,
	[SYS_setsockopt] = 0,
	[SYS_set_thread_area] = 0,
	[SYS_set_thread_area] = 0,
	[SYS_set_tid_address] = 0,
	[SYS_settimeofday] = 0,
	[SYS_setuid32] = 0,
	[SYS_setuid] = 0,
	[SYS_setxattr] = 0,
	[SYS_sgetmask] = 0,
	[SYS_shutdown] = 0,
	[SYS_sigaction] = 0,
	[SYS_sigaltstack] = 0,
	[SYS_signalfd4] = 0,
	[SYS_signalfd] = 0,
	[SYS_signal] = 0,
	[SYS_sigpending] = 0,
	[SYS_sigprocmask] = 0,
	[SYS_sigreturn] = 0,
	[SYS_sigsuspend] = 0,
	[SYS_socketcall] = 0,
	[SYS_socketpair] = 0,
	[SYS_socket_subcall + 1] = 0,
	[SYS_splice] = 0,
	[SYS_ssetmask] = 0,
	[SYS_stat64] = 0,
	[SYS_statfs64] = 0,
	[SYS_statfs] = 0,
	[SYS_stat] = 0,
	[SYS_stime] = 0,
	[SYS_stty] = 0,
	[SYS_swapoff] = 0,
	[SYS_swapon] = 0,
	[SYS_symlinkat] = 0,
	[SYS_symlink] = 0,
	[SYS_sync_file_range] = 0,
	[SYS_syncfs] = 0,
	[SYS_sync] = 0,
	[SYS__sysctl] = 0,
	[SYS_sysfs] = 0,
	[SYS_sysinfo] = 0,
	[SYS_syslog] = 0,
	[SYS_tee] = 0,
	[SYS_tgkill] = 0,
	[SYS_timer_create] = 0,
	[SYS_timer_delete] = 0,
	[SYS_timerfd_create] = 0,
	[SYS_timerfd_gettime] = 0,
	[SYS_timerfd_settime] = 0,
	[SYS_timer_getoverrun] = 0,
	[SYS_timer_gettime] = 0,
	[SYS_timer_settime] = 0,
	[SYS_times] = 0,
	[SYS_time] = 0,
	[SYS_tkill] = 0,
	[SYS_truncate64] = 0,
	[SYS_truncate] = 0,
	[SYS_ugetrlimit] = 0,
	[SYS_ulimit] = 0,
	[SYS_umask] = 0,
	[SYS_umount2] = 0,
	[SYS_umount] = 0,
	[SYS_uname] = 0,
	[SYS_unlinkat] = 0,
	[SYS_unlink] = 0,
	[SYS_unshare] = 0,
	[SYS_uselib] = 0,
	[SYS_ustat] = 0,
	[SYS_utimensat] = 0,
	[SYS_utimes] = 0,
	[SYS_utime] = 0,
	[SYS_vfork] = 0,
	[SYS_vhangup] = 0,
	[SYS_vm86old] = 0,
	[SYS_vm86] = 0,
	[SYS_vmsplice] = 0,
	[SYS_vserver] = 0,
	[SYS_wait4] = 0,
	[SYS_waitid] = 0,
	[SYS_waitpid] = 0,
	[SYS_write] = 0,
	[SYS_writev] = 0,


	[SYS_semop] = 0,
	[SYS_semget] = 0,
	[SYS_semctl] = 0,
	[SYS_semtimedop] = 0,
	[SYS_ipc_subcall] = 0,
	[SYS_msgsnd] = 0,
	[SYS_msgrcv] = 0,
	[SYS_msgget] = 0,
	[SYS_msgctl] = 0,
	[SYS_shmat] = 0,
	[SYS_shmdt] = 0,
	[SYS_shmget] = 0,
	[SYS_shmctl] = 0,

};
