#include "usagecontrol.h"


void ucInit() {
#ifdef UC_SEMANTICS_H_
	ucSemantics__init();
#endif

#ifdef UC_DECLASS_H_
	ucDeclass__init();
#endif

	ucPIP_init();

	ucPIP_addInitialData("/tmp/foo");
}

// Kelbert
int ucBeforeSyscallEnter(struct tcb *tcp) {
	int retval = ucPDPask(tcp);

	switch(retval) {
		case UC_PDP_ALLOW:
		case UC_PDP_MODIFY:	// modify assumes that the syscall has already been modified transparently		
			if (ucPIPupdateBefore(tcp)) {
				if (ucSemanticsFunct[tcp->scno]) {
					ucSemanticsFunct[tcp->scno](tcp);
#if UC_DECLASS_ENABLED
//					ucDeclassEvent(tcp);
#endif
//					ucPIP_printF();
//					ucPIP_printS();
				}
				else {
//					fprintf(stderr, "Unhandled %s (%ld)\n", tcp->s_ent->sys_name, tcp->scno);
				}
			}
			break;
		case UC_PDP_INHIBIT:
			// TODO: write code
			break;
		case UC_PDP_DELAY:
			// TODO: write code
			break;
	}

	return (retval);
}

// Kelbert
int ucAfterSyscallExit(struct tcb *tcp) {
	int retval = ucPDPask(tcp);

	switch(retval) {
		case UC_PDP_ALLOW:		
			if (ucPIPupdateAfter(tcp)) {
				if (ucSemanticsFunct[tcp->scno]) {
					ucSemanticsFunct[tcp->scno](tcp);
#if UC_DECLASS_ENABLED
//					ucDeclassEvent(tcp);
#endif
//					ucPIP_printF();
//					ucPIP_printS();
				}
				else {
//					fprintf(stderr, "Unhandled %s (%ld)\n", tcp->s_ent->sys_name, tcp->scno);
				}
			}
			break;
		case UC_PDP_DELAY:
		case UC_PDP_MODIFY:
		case UC_PDP_INHIBIT:
			// TODO: does it make sense to modify/delay/inhibit after the call has been executed???
			break;
	}

	return (retval);
}





void (*ucSemanticsFunct[])(struct tcb *tcp) = {
	[SYS_accept] = ucSemantics_accept,
	[SYS_access] = NULL,
	[SYS_acct] = NULL,
	[SYS_add_key] = NULL,
	[SYS_adjtimex] = NULL,
	[SYS_afs_syscall] = NULL,
	[SYS_alarm] = NULL,
	[SYS_bdflush] = NULL,
	[SYS_bind] = NULL,
	[SYS_break] = NULL,
	[SYS_brk] = NULL,
	[SYS_capget] = NULL,
	[SYS_capset] = NULL,
	[SYS_chdir] = NULL,
	[SYS_chmod] = NULL,
	[SYS_chown32] = NULL,
	[SYS_chown] = NULL,
	[SYS_chroot] = NULL,
	[SYS_clock_adjtime] = NULL,
	[SYS_clock_getres] = NULL,
	[SYS_clock_gettime] = NULL,
	[SYS_clock_nanosleep] = NULL,
	[SYS_clock_settime] = NULL,
	[SYS_clone] = NULL,								// we handle clone differently...
	[SYS_close] = ucSemantics_close,
	[SYS_connect] = ucSemantics_connect,
	[SYS_create_module] = NULL,
	[SYS_creat] = NULL,
	[SYS_delete_module] = NULL,
	[SYS_dup2] = ucSemantics_dup2,
	[SYS_dup3] = ucSemantics_dup2,
	[SYS_dup] = ucSemantics_dup,
	[SYS_epoll_create1] = NULL,
	[SYS_epoll_create] = NULL,
	[SYS_epoll_ctl] = NULL,
	[SYS_epoll_pwait] = NULL,
	[SYS_epoll_wait] = NULL,
	[SYS_eventfd2] = ucSemantics_eventfd,
	[SYS_eventfd] = ucSemantics_eventfd,
	[SYS_execve] = ucSemantics_execve,
	[SYS_exit_group] = ucSemantics_exit_group,
	[SYS_exit] = ucSemantics_exit,
	[SYS_faccessat] = NULL,
	[SYS_fadvise64_64] = NULL,
	[SYS_fadvise64] = NULL,
	[SYS_fallocate] = NULL,
	[SYS_fanotify_init] = NULL,
	[SYS_fanotify_mark] = NULL,
	[SYS_fchdir] = NULL,
	[SYS_fchmodat] = NULL,
	[SYS_fchmod] = NULL,
	[SYS_fchown32] = NULL,
	[SYS_fchownat] = NULL,
	[SYS_fchown] = NULL,
	[SYS_fcntl64] = ucSemantics_fcntl,
	[SYS_fcntl] = ucSemantics_fcntl,
	[SYS_fdatasync] = NULL,
	[SYS_fgetxattr] = NULL,
	[SYS_flistxattr] = NULL,
	[SYS_flock] = NULL,
	[SYS_fork] = ucSemantics_IGNORE,
	[SYS_fremovexattr] = NULL,
	[SYS_fsetxattr] = NULL,
	[SYS_fstat64] = NULL,
	[SYS_fstatat64] = NULL,
	[SYS_fstatfs64] = NULL,
	[SYS_fstatfs] = NULL,
	[SYS_fstat] = NULL,
	[SYS_fsync] = NULL,
	[SYS_ftime] = NULL,
	[SYS_ftruncate64] = ucSemantics_ftruncate,
	[SYS_ftruncate] = ucSemantics_ftruncate,
	[SYS_futex] = NULL,
	[SYS_futimesat] = NULL,
	[SYS_getcpu] = NULL,
	[SYS_getcwd] = NULL,
	[SYS_getdents64] = NULL,
	[SYS_getdents] = NULL,
	[SYS_getegid32] = NULL,
	[SYS_getegid] = NULL,
	[SYS_geteuid32] = NULL,
	[SYS_geteuid] = NULL,
	[SYS_getgid32] = NULL,
	[SYS_getgid] = NULL,
	[SYS_getgroups32] = NULL,
	[SYS_getgroups] = NULL,
	[SYS_getitimer] = NULL,
	[SYS_get_kernel_syms] = NULL,
	[SYS_get_mempolicy] = NULL,
	[SYS_getpeername] = NULL,
	[SYS_getpgid] = NULL,
	[SYS_getpgrp] = NULL,
	[SYS_getpid] = NULL,
	[SYS_getpmsg] = NULL,
	[SYS_getppid] = NULL,
	[SYS_getpriority] = NULL,
	[SYS_getresgid32] = NULL,
	[SYS_getresgid] = NULL,
	[SYS_getresuid32] = NULL,
	[SYS_getresuid] = NULL,
	[SYS_getrlimit] = NULL,
	[SYS_get_robust_list] = NULL,
	[SYS_getrusage] = NULL,
	[SYS_getsid] = NULL,
	[SYS_getsockname] = NULL,
	[SYS_getsockopt] = NULL,
	[SYS_get_thread_area] = NULL,
	[SYS_gettid] = NULL,
	[SYS_gettimeofday] = ucSemantics_IGNORE,
	[SYS_getuid32] = NULL,
	[SYS_getuid] = NULL,
	[SYS_getxattr] = NULL,
	[SYS_gtty] = NULL,
	[SYS_idle] = NULL,
	[SYS_init_module] = NULL,
	[SYS_inotify_add_watch] = NULL,
	[SYS_inotify_init1] = NULL,
	[SYS_inotify_init] = NULL,
	[SYS_inotify_rm_watch] = NULL,
	[SYS_io_cancel] = NULL,
	[SYS_ioctl] = NULL,
	[SYS_io_destroy] = NULL,
	[SYS_io_getevents] = NULL,
	[SYS_ioperm] = NULL,
	[SYS_iopl] = NULL,
	[SYS_ioprio_get] = NULL,
	[SYS_ioprio_set] = NULL,
	[SYS_io_setup] = NULL,
	[SYS_io_submit] = NULL,
	[SYS_ipc] = NULL,
	[SYS_kexec_load] = NULL,
	[SYS_keyctl] = NULL,
	[SYS_kill] = ucSemantics_kill,
	[SYS_lchown32] = NULL,
	[SYS_lchown] = NULL,
	[SYS_lgetxattr] = NULL,
	[SYS_linkat] = NULL,
	[SYS_link] = NULL,
	[SYS_listen] = NULL,
	[SYS_listxattr] = NULL,
	[SYS_llistxattr] = NULL,
	[SYS__llseek] = NULL,
	[SYS__llseek] = NULL,
	[SYS_lock] = NULL,
	[SYS_lookup_dcookie] = NULL,
	[SYS_lremovexattr] = NULL,
	[SYS_lseek] = NULL,
	[SYS_lsetxattr] = NULL,
	[SYS_lstat64] = NULL,
	[SYS_lstat] = NULL,
	[SYS_madvise] = NULL,
	[SYS_mbind] = NULL,
	[SYS_migrate_pages] = NULL,
	[SYS_mincore] = NULL,
	[SYS_mkdirat] = NULL,
	[SYS_mkdir] = NULL,
	[SYS_mknodat] = NULL,
	[SYS_mknod] = NULL,
	[SYS_mlockall] = NULL,
	[SYS_mlock] = NULL,
	[SYS_mmap2] = ucSemantics_mmap,
	[SYS_mmap] = ucSemantics_mmap,
	[SYS_modify_ldt] = NULL,
	[SYS_mount] = NULL,
	[SYS_move_pages] = NULL,
	[SYS_mprotect] = NULL,
	[SYS_mpx] = NULL,
	[SYS_mq_getsetattr] = NULL,
	[SYS_mq_notify] = NULL,
	[SYS_mq_open ] = NULL,
	[SYS_mq_timedreceive] = NULL,
	[SYS_mq_timedsend] = NULL,
	[SYS_mq_unlink] = ucSemantics_unlink,
	[SYS_mremap] = NULL,
	[SYS_msync] = NULL,
	[SYS_munlockall] = NULL,
	[SYS_munlock] = NULL,
	[SYS_munmap] = ucSemantics_munmap,
	[SYS_name_to_handle_at] = NULL,
	[SYS_nanosleep] = NULL,
	[SYS__newselect] = NULL,
	[SYS_nfsservctl] = NULL,
	[SYS_nice] = NULL,
	[SYS_oldfstat] = NULL,
	[SYS_oldlstat] = NULL,
	[SYS_oldolduname] = NULL,
	[SYS_oldstat] = NULL,
	[SYS_olduname] = NULL,
	[SYS_openat] = ucSemantics_openat,
	[SYS_open_by_handle_at] = NULL,
	[SYS_open] = ucSemantics_open,
	[SYS_pause] = NULL,
	[SYS_perf_event_open] = NULL,
	[SYS_personality] = NULL,
	[SYS_pipe2] = ucSemantics_pipe,
	[SYS_pipe] = ucSemantics_pipe,
	[SYS_pivot_root] = NULL,
	[SYS_poll] = ucSemantics_IGNORE,
	[SYS_ppoll] = NULL,
	[SYS_prctl] = NULL,
	[SYS_pread64] = ucSemantics_read,
	[SYS_preadv] = ucSemantics_read,
	[SYS_prlimit64] = NULL,
	[SYS_process_vm_readv] = NULL,
	[SYS_process_vm_writev] = NULL,
	[SYS_profil] = NULL,
	[SYS_prof] = NULL,
	[SYS_pselect6] = NULL,
	[SYS_ptrace] = NULL,
	[SYS_putpmsg] = NULL,
	[SYS_pwrite64] = ucSemantics_write,
	[SYS_pwritev] = ucSemantics_write,
	[SYS_query_module] = NULL,
	[SYS_quotactl] = NULL,
	[SYS_readahead] = NULL,
	[SYS_readdir] = NULL,
	[SYS_readlinkat] = NULL,
	[SYS_readlink] = NULL,
	[SYS_read] = ucSemantics_read,
	[SYS_readv] = ucSemantics_read,
	[SYS_reboot] = NULL,
	[SYS_recvfrom] = ucSemantics_read,
	[SYS_recvmmsg] = ucSemantics_read,
	[SYS_recvmsg] = ucSemantics_read,
	[SYS_recv] = ucSemantics_read,
	[SYS_remap_file_pages] = NULL,
	[SYS_removexattr] = NULL,
	[SYS_renameat] = NULL,
	[SYS_rename] = ucSemantics_rename,
	[SYS_request_key] = NULL,
	[SYS_restart_syscall] = NULL,
	[SYS_rmdir] = NULL,
	[SYS_rt_sigaction] = NULL,
	[SYS_rt_sigaction] = NULL,
	[SYS_rt_sigpending] = NULL,
	[SYS_rt_sigprocmask] = NULL,
	[SYS_rt_sigqueueinfo] = NULL,
	[SYS_rt_sigreturn] = NULL,
	[SYS_rt_sigsuspend] = NULL,
	[SYS_rt_sigtimedwait] = NULL,
	[SYS_rt_tgsigqueueinfo] = NULL,
	[SYS_sched_getaffinity] = NULL,
	[SYS_sched_getparam] = NULL,
	[SYS_sched_get_priority_max] = NULL,
	[SYS_sched_get_priority_min] = NULL,
	[SYS_sched_getscheduler] = NULL,
	[SYS_sched_rr_get_interval] = NULL,
	[SYS_sched_setaffinity] = NULL,
	[SYS_sched_setparam] = NULL,
	[SYS_sched_setscheduler] = NULL,
	[SYS_sched_yield] = NULL,
	[SYS_select] = NULL,
	[SYS_sendfile64] = NULL,
	[SYS_sendfile] = NULL,
	[SYS_sendmmsg] = ucSemantics_write,
	[SYS_sendmsg] = ucSemantics_write,
	[SYS_send] = ucSemantics_write,
	[SYS_sendto] = ucSemantics_write,
	[SYS_setdomainname] = NULL,
	[SYS_setfsgid32] = NULL,
	[SYS_setfsgid] = NULL,
	[SYS_setfsuid32] = NULL,
	[SYS_setfsuid] = NULL,
	[SYS_setgid32] = NULL,
	[SYS_setgid] = NULL,
	[SYS_setgroups32] = NULL,
	[SYS_setgroups] = NULL,
	[SYS_sethostname] = NULL,
	[SYS_setitimer] = NULL,
	[SYS_set_mempolicy] = NULL,
	[SYS_setns] = NULL,
	[SYS_setpgid] = NULL,
	[SYS_setpriority] = NULL,
	[SYS_setregid32] = NULL,
	[SYS_setregid] = NULL,
	[SYS_setresgid32] = NULL,
	[SYS_setresgid] = NULL,
	[SYS_setresuid32] = NULL,
	[SYS_setresuid] = NULL,
	[SYS_setreuid32] = NULL,
	[SYS_setreuid] = NULL,
	[SYS_setrlimit] = NULL,
	[SYS_set_robust_list] = NULL,
	[SYS_setsid] = NULL,
	[SYS_setsockopt] = NULL,
	[SYS_set_thread_area] = NULL,
	[SYS_set_thread_area] = NULL,
	[SYS_set_tid_address] = NULL,
	[SYS_settimeofday] = NULL,
	[SYS_setuid32] = NULL,
	[SYS_setuid] = NULL,
	[SYS_setxattr] = NULL,
	[SYS_sgetmask] = NULL,
	[SYS_shutdown] = ucSemantics_shutdown,
	[SYS_sigaction] = NULL,
	[SYS_sigaltstack] = NULL,
	[SYS_signalfd4] = NULL,
	[SYS_signalfd] = NULL,
	[SYS_signal] = NULL,
	[SYS_sigpending] = NULL,
	[SYS_sigprocmask] = NULL,
	[SYS_sigreturn] = NULL,
	[SYS_sigsuspend] = NULL,
	[SYS_socketcall] = NULL,
	[SYS_socketpair] = ucSemantics_socketpair,
	[SYS_socket_subcall + 1] = ucSemantics_socket,
	[SYS_splice] = ucSemantics_splice,
	[SYS_ssetmask] = NULL,
	[SYS_stat64] = NULL,
	[SYS_statfs64] = NULL,
	[SYS_statfs] = NULL,
	[SYS_stat] = NULL,
	[SYS_stime] = NULL,
	[SYS_stty] = NULL,
	[SYS_swapoff] = NULL,
	[SYS_swapon] = NULL,
	[SYS_symlinkat] = NULL,
	[SYS_symlink] = NULL,
	[SYS_sync_file_range] = NULL,
	[SYS_syncfs] = NULL,
	[SYS_sync] = NULL,
	[SYS__sysctl] = NULL,
	[SYS_sysfs] = NULL,
	[SYS_sysinfo] = NULL,
	[SYS_syslog] = NULL,
	[SYS_tee] = NULL,
	[SYS_tgkill] = NULL,
	[SYS_timer_create] = NULL,
	[SYS_timer_delete] = NULL,
	[SYS_timerfd_create] = NULL,
	[SYS_timerfd_gettime] = NULL,
	[SYS_timerfd_settime] = NULL,
	[SYS_timer_getoverrun] = NULL,
	[SYS_timer_gettime] = NULL,
	[SYS_timer_settime] = NULL,
	[SYS_times] = NULL,
	[SYS_time] = NULL,
	[SYS_tkill] = NULL,
	[SYS_truncate64] = NULL,
	[SYS_truncate] = NULL,
	[SYS_ugetrlimit] = NULL,
	[SYS_ulimit] = NULL,
	[SYS_umask] = NULL,
	[SYS_umount2] = NULL,
	[SYS_umount] = NULL,
	[SYS_uname] = NULL,
	[SYS_unlinkat] = NULL,
	[SYS_unlink] = NULL,
	[SYS_unshare] = NULL,
	[SYS_uselib] = NULL,
	[SYS_ustat] = NULL,
	[SYS_utimensat] = NULL,
	[SYS_utimes] = NULL,
	[SYS_utime] = NULL,
	[SYS_vfork] = ucSemantics_IGNORE,
	[SYS_vhangup] = NULL,
	[SYS_vm86old] = NULL,
	[SYS_vm86] = NULL,
	[SYS_vmsplice] = NULL,
	[SYS_vserver] = NULL,
	[SYS_wait4] = ucSemantics_IGNORE,
	[SYS_waitid] = ucSemantics_IGNORE,
	[SYS_waitpid] = ucSemantics_IGNORE,
	[SYS_write] = ucSemantics_write,
	[SYS_writev] = ucSemantics_write,


	[SYS_semop] = NULL,
	[SYS_semget] = NULL,
	[SYS_semctl] = NULL,
	[SYS_semtimedop] = NULL,
	[SYS_ipc_subcall] = NULL,
	[SYS_msgsnd] = NULL,
	[SYS_msgrcv] = NULL,
	[SYS_msgget] = NULL,
	[SYS_msgctl] = NULL,
	[SYS_shmat] = NULL,
	[SYS_shmdt] = NULL,
	[SYS_shmget] = NULL,
	[SYS_shmctl] = NULL,

	[SYS_cloneFirstAction] = ucSemantics_cloneFirstAction

};
