/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_fhg_iese_esf_pdp_PolicyDecisionPointNative */

#ifndef _Included_de_fhg_iese_esf_pdp_PolicyDecisionPointNative
#define _Included_de_fhg_iese_esf_pdp_PolicyDecisionPointNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_fhg_iese_esf_pdp_PolicyDecisionPointNative
 * Method:    start
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_fhg_iese_esf_pdp_PolicyDecisionPointNative_start
  (JNIEnv *, jobject);

/*
 * Class:     de_fhg_iese_esf_pdp_PolicyDecisionPointNative
 * Method:    stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_fhg_iese_esf_pdp_PolicyDecisionPointNative_stop
  (JNIEnv *, jobject);

/*
 * Class:     de_fhg_iese_esf_pdp_PolicyDecisionPointNative
 * Method:    notifyEventXML
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_fhg_iese_esf_pdp_PolicyDecisionPointNative_notifyEventXML
  (JNIEnv *, jobject, jstring);

/*
 * Class:     de_fhg_iese_esf_pdp_PolicyDecisionPointNative
 * Method:    deployMechanism
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_fhg_iese_esf_pdp_PolicyDecisionPointNative_deployMechanism
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
