# libraries/thread/SConscript
import os, sys
Import('env','curBaseDir')

threadObject=env.rdObject('threadUtils.c', ccflags = env['CCFLAGS']+'-fno-builtin ')
Alias('pefThreadUtils', threadObject)

Alias('thread', threadObject)




