import os
Import('env')

# Preparing RMI server
newpath=os.environ.get('PATH')
env.Append(ENV = {'PATH':newpath})

targetDir=os.path.join(env['PEFBUILD'],"..","java")
sourceDir=os.path.join(env['PEFBASE'], "..","java","jpdp","de","fraunhofer","iese","pef","pdp")

rmiClasses=env.Java(target=targetDir, source='.')
#rmiClasses=env.Java(target=targetDir, 
#                    source=[os.path.join(sourceDir, "IPolicyDecisionPoint.java"),
#                            os.path.join(sourceDir, "PolicyDecisionPoint.java"),
#                            os.path.join(sourceDir, "internal", "AuthorizationAction.java"),
#                            os.path.join(sourceDir, "internal", "Constants.java"),
#                            os.path.join(sourceDir, "internal", "Decision.java"),
#                            os.path.join(sourceDir, "internal", "Event.java"),
#                            os.path.join(sourceDir, "internal", "ExecuteAction.java"),
#                            os.path.join(sourceDir, "internal", "Param.java"),
#                            os.path.join(sourceDir, "internal", "xml", "DecisionParser.java"),
#                            os.path.join(sourceDir, "internal", "xml", "EventParser.java"),
#                            os.path.join(sourceDir, "internal", "xml", "XmlUtils.java"),
#                            os.path.join(sourceDir, "rmiServer", "pdpRMIserver.java")
#                           ])

rmiStub=env.RMIC(target=os.path.join(targetDir), source=os.path.join(targetDir, "de", "fraunhofer", "iese", "pef", "pdp", "PolicyDecisionPoint"))
rmiJar=env.Jar(target=os.path.join(targetDir, 'rmiServer.jar'), source=[rmiClasses, rmiStub, os.path.join(sourceDir, "rmiServer", "Manifest")])

rmiClientJar=env.Jar(target=os.path.join(targetDir, 'rmiClient.jar'), 
                     source=[rmiStub, 
                             os.path.join(targetDir, "de", "fraunhofer", "iese", "pef", "pdp", "internal","IPolicyDecisionPoint.class"),
                             os.path.join(targetDir, "de", "fraunhofer", "iese", "pef", "pdp", "internal","AuthorizationAction.class"),
                             os.path.join(targetDir, "de", "fraunhofer", "iese", "pef", "pdp", "internal","Constants.class"),
                             os.path.join(targetDir, "de", "fraunhofer", "iese", "pef", "pdp", "internal","Decision.class"),
                             os.path.join(targetDir, "de", "fraunhofer", "iese", "pef", "pdp", "internal","Event.class"),
                             os.path.join(targetDir, "de", "fraunhofer", "iese", "pef", "pdp", "internal","ExecuteAction.class"),
                             os.path.join(targetDir, "de", "fraunhofer", "iese", "pef", "pdp", "internal","Param.class"),
                             os.path.join(targetDir, "de", "fraunhofer", "iese", "pef", "pdp", "internal","xml","DecisionParser.class"),
                             os.path.join(targetDir, "de", "fraunhofer", "iese", "pef", "pdp", "internal","xml","EventParser.class"),
                             os.path.join(targetDir, "de", "fraunhofer", "iese", "pef", "pdp", "internal","xml","XmlUtils.class"),
                            ])

Alias('rmiClasses', [rmiClasses,rmiJar, rmiStub, rmiClientJar])

