# applications/systracePEP/shell_wrapper/SConscript
import os, sys
Import('env','curBaseDir')

if sys.platform == "openbsd5":
	logfiles = env.checkLogger(curBaseDir)

	shellWrapper=env.Program('shell_wrapper.c', LIBS=env['LIBS']+['logger','socket_utils','mem_utils'])
	Depends(shellWrapper, ['logger','utilities'])
	Clean(shellWrapper,logfiles['shell_wrapper.c'])

	Alias('shellWrapper', [shellWrapper])
else:
	print "Skipping not supported shellWrapper"
	Alias('shellWrapper', [])

