<message name="remoteAttestationRequest">
  <part name="attestationProperties" type="xs:array"/>
</message>

<message name="remoteAttestationResponse">
  <part name="attestationValues" type="xs:array"/>
</message>

<portType name="remoteAttestation">
  <operation name="doRemoteAttestation">
    <input message="remoteAttestationRequest"/>
    <output message="remoteAttestationResponse"/>
  </operation>
</portType>

<binding type="attestationService" name="b1">
   <soap:binding style="document"
   transport="http://schemas.xmlsoap.org/soap/http" />
   <operation>
     <soap:operation soapAction="remoteAttestation"/>
     <input><soap:body use="literal"/></input>
     <output><soap:body use="literal"/></output>
  </operation>
</binding>