# libraries/action/SConscript
import os
Import('env','curBaseDir')

logfiles = env.checkLogger(curBaseDir)

actionStatic=env.StaticLibrary('action','action.c', CCFLAGS=env['CCFLAGS']+' -fPIC ')
Clean(actionStatic,logfiles['action.c'])
env.Append(ESF_action = actionStatic)

Alias('action', actionStatic)
