# libraries/event/SConscript
import os
Import('env','curBaseDir')

logfiles = env.checkLogger(curBaseDir)

esfeventStatic = env.StaticLibrary('esfevent','esfevent.c', CCFLAGS=env['CCFLAGS']+' -fPIC ')
Clean(esfeventStatic,logfiles['esfevent.c'])
env.Append(ESF_esfevent = esfeventStatic)

Alias('esfevent', esfeventStatic)
