import os
env=SConscript('SConscript')

libpath=os.path.join(env['ESFBASE'], "libraries")
comppath=os.path.join(env['ESFBASE'], "components")
apppath=os.path.join(env['ESFBASE'], "applications")

for f in os.listdir(libpath):
  if os.path.isdir(os.path.join(libpath, f)):
    if f == ".svn":
      continue
    curBaseDir = os.path.join(libpath, f)
    SConscript(dirs=curBaseDir, exports=['env','curBaseDir'], variant_dir = env['ESFBUILD']+'/libraries/'+f, duplicate = False)

for f in os.listdir(comppath):
  if os.path.isdir(os.path.join(comppath, f)):
    if f == ".svn":
      continue
    curBaseDir = os.path.join(comppath, f)
    SConscript(dirs=curBaseDir, exports=['env','curBaseDir'], variant_dir = env['ESFBUILD']+'/components/'+f, duplicate = False)

for f in os.listdir(apppath):
  if os.path.isdir(os.path.join(apppath, f)):
    if f == ".svn":
      continue
    curBaseDir = os.path.join(apppath, f)
    SConscript(dirs=curBaseDir, exports=['env','curBaseDir'], variant_dir = env['ESFBUILD']+'/applications/'+f, duplicate = False)

# deactivated for openbsd
#docroot=os.path.join(env['ESFBASE'],'..','..','site','doc','axis2c')
#fhg_esf_docs = env.Doxygen("FhG-ESF.doxyfile")
#fhg_esf_doc_pdf = env.PDF(docroot + '/pdf/fhg_esf.pdf', os.path.join(docroot, 'latex') + '/refman.tex')
##Depends(fhg_esf_doc_pdf, fhg_esf_docs)
#Alias('doc', [fhg_esf_docs,fhg_esf_doc_pdf])
#Clean(fhg_esf_docs, env.listDirRecursive(os.path.join(env['ESFBASE'],'..','..','site','doc','axis2c')))
