# applications/examples/SConscript
import os, sys
Import('env','curBaseDir')

lexamples = []
if env['android']==True:
  Alias('examples', lexamples)
  Return()
  
if env['PEFCONFIG']['examples'] == False:
  Alias('examples', lexamples)
  Return()
  
#if sys.platform!="win32":
#	pdpXMLRPCtest=env.Program('pdpXMLrpcTest.c', LIBS=['logger','action',
#    	                                                'soup-2.4','soupUtils','memUtils','pthread']+env['LIBS'])
#	Depends(pdpXMLRPCtest, ['logger', 'utilities'])
#	lexamples.append(pdpXMLRPCtest)

regexExample=env.Program('exRegex.c', LIBS=env['LIBS'])
lexamples.append(regexExample)

if env['PEFCONFIG']['socketUtils']==True:
  if sys.platform=="win32":
    socketTCPserverObject=env.rdObject('socketTCPserver.c')
    socketTCPserver=env.Program([socketTCPserverObject, env['pefSocketUtils'], env.getAliasObjects('logger'), env.getAliasObjects('pefMemUtils'), env.getAliasObjects('pefThreadUtils')], LIBS=['ws2_32','wsock32'] + env['LIBS'])
    Depends(socketTCPserver, ['logger', 'utilities'])
    lexamples.append(socketTCPserver)

    socketTCPclientObject=env.rdObject('socketTCPclient.c')
    socketTCPclient=env.Program([socketTCPclientObject, env.getAliasObjects('logger'), env['pefSocketUtils'], env.getAliasObjects('pefMemUtils'), env.getAliasObjects('pefThreadUtils')], LIBS=['ws2_32','wsock32'] + env['LIBS'])
    Depends(socketTCPclient, ['logger', 'utilities'])
    lexamples.append(socketTCPclient)

    #pdpSocketClientObject=env.rdObject('pdpSocketClient.c')
    #pdpSocketClient2=env.Program([pdpSocketClientObject, env.getAliasObjects('logger'), env.getAliasObjects('pefSocketUtils'), 
    #                              env.getAliasObjects('pefMemUtils'), env.getAliasObjects('pefThreadUtils')], 
    #                              LIBS=['ws2_32','wsock32'] + env['LIBS'])
    #Depends(pdpSocketClient, ['logger', 'utilities'])
    #lexamples.append(pdpSocketClient)  
  
  else:
    pdpSocketClientObject=env.rdObject('pdpSocketClient.c')
    pdpSocketClient=env.Program([pdpSocketClientObject, env.getAliasObjects('logger'), env.getAliasObjects('pefSocketUtils'), 
                                env.getAliasObjects('pefMemUtils'), env.getAliasObjects('pefThreadUtils')], 
                             LIBS=env['LIBS'])
    Depends(pdpSocketClient, ['logger', 'utilities'])
    lexamples.append(pdpSocketClient)
  
    socketTCPserverObject=env.rdObject('socketTCPserver.c')
    socketTCPserver=env.Program([socketTCPserverObject, env['pefSocketUtils'], env.getAliasObjects('logger'), env.getAliasObjects('pefMemUtils'), env.getAliasObjects('pefThreadUtils')], 
                                      LIBS=env['LIBS'])
    Depends(socketTCPserver, ['logger', 'utilities'])
    lexamples.append(socketTCPserver)
    
    socketTCPclientObject=env.rdObject('socketTCPclient.c')
    socketTCPclient=env.Program([socketTCPclientObject, env.getAliasObjects('logger'), env['pefSocketUtils'], env.getAliasObjects('pefMemUtils'), env.getAliasObjects('pefThreadUtils')], 
                                  LIBS=env['LIBS'])
    Depends(socketTCPclient, ['logger', 'utilities'])
    lexamples.append(socketTCPclient)


Default(lexamples)
Alias('examples', lexamples)





