/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_fhg_iese_esf_as_AttestationServiceNative */

#ifndef _Included_de_fhg_iese_esf_as_AttestationServiceNative
#define _Included_de_fhg_iese_esf_as_AttestationServiceNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_fhg_iese_esf_as_AttestationServiceNative
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_fhg_iese_esf_as_AttestationServiceNative_start
  (JNIEnv *, jobject);

/*
 * Class:     de_fhg_iese_esf_as_AttestationServiceNative
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_fhg_iese_esf_as_AttestationServiceNative_stop
  (JNIEnv *, jobject);

/*
 * Class:     de_fhg_iese_esf_as_AttestationServiceNative
 * Method:    attestFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_fhg_iese_esf_as_AttestationServiceNative_attestFile
  (JNIEnv *, jobject, jstring, jstring, jstring, jint);

/*
 * Class:     de_fhg_iese_esf_as_AttestationServiceNative
 * Method:    getAikCertificate
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_fhg_iese_esf_as_AttestationServiceNative_getAikCertificate
  (JNIEnv *, jobject);

/*
 * Class:     de_fhg_iese_esf_as_AttestationServiceNative
 * Method:    getQuotedPCRs
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_fhg_iese_esf_as_AttestationServiceNative_getQuotedPCRs
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
