<?xml version="1.0" encoding="UTF-8"?>
<definitions
  name            = "Calculator"
  targetNamespace = "http://www.iese.fhg.de/esf/1.0/calc/ws"
  xmlns:tns       = "http://www.iese.fhg.de/esf/1.0/calc/ws"  
  xmlns:tnss      = "http://www.iese.fhg.de/esf/1.0/calc/ws/schema"
  xmlns:wsdl      = "http://schemas.xmlsoap.org/wsdl/"
  xmlns:soap      = "http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:xsd       = "http://www.w3.org/2001/XMLSchema" 
  xmlns           = "http://schemas.xmlsoap.org/wsdl/">
  
  <types>
    <xsd:schema>
      <xsd:import namespace="http://www.iese.fhg.de/esf/1.0/calc/ws/schema"
                  schemaLocation="calculator.xsd"/>
    </xsd:schema>
  </types>
  
  <message name="AddIntegersInMsg">
    <part name="AddIntegersRequestPart" element="tnss:addIntegersRequest"/>
  </message>
  
  <message name="AddIntegersOutMsg">
    <part name="AddIntegersResponsePart" element="tnss:addIntegersResponse"/>
  </message>
  
  <portType name="CalculatorInterface">
    <operation name="addIntegers">
      <input message="tns:AddIntegersInMsg" />
      <output message="tns:AddIntegersOutMsg" />
    </operation>
  </portType>
  
  <binding name="CalculatorSOAP" type="tns:CalculatorInterface">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
    <operation name="addIntegers">
      <soap:operation soapAction="addIntegers" style="document"/>
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
  </binding>
  
  <service name="Calculator">
    <port binding="tns:CalculatorSOAP" name="CalculatorSOAP">
      <soap:address location="http://127.0.0.1:8080/FhG_WebServices/services/Calculator" />
    </port>
  </service>
  
</definitions>