# components/dataCont/SConscript
import os
Import('env','curBaseDir')

logfiles = env.checkLogger(curBaseDir)

listOfEventsStatic=env.StaticLibrary('list_of_events.c', CCFLAGS=env['CCFLAGS']+' -fPIC ')
Clean(listOfEventsStatic, logfiles['list_of_events.c'])
env.Append(ESF_listOfEvents = listOfEventsStatic)

dataContStatic=env.StaticLibrary('dataCont.c', CCFLAGS=env['CCFLAGS']+' -fPIC ')
Depends(dataContStatic, ['esfevent'])
Clean(dataContStatic, logfiles['dataCont.c'])
env.Append(ESF_dataCont = dataContStatic)

qdftConnectorShared=env.SharedLibrary('qdftConnector.cc')
#Clean(qdftConnectorShared, logfiles['qdftConnector.cc'])
env.Append(ESF_qdftConnector = qdftConnectorShared)

dataFlowMonitorStatic=env.StaticLibrary('data_flow_monitor.c', CCFLAGS=env['CCFLAGS']+' -fPIC ')
Depends(dataFlowMonitorStatic, [dataContStatic, qdftConnectorShared])
Clean(dataFlowMonitorStatic, logfiles['data_flow_monitor.c'])
env.Append(ESF_dataFlowMonitor = dataFlowMonitorStatic)

env.Alias('datacont', [listOfEventsStatic, dataContStatic, dataFlowMonitorStatic, qdftConnectorShared])

