# libraries/timestamp/SConscript
import os
Import('env','curBaseDir')

logfiles = env.checkLogger(curBaseDir)

timestampStatic = env.StaticLibrary('timestamp', 'timestamp.c', CCFLAGS=env['CCFLAGS']+' -fPIC ')
Clean(timestampStatic,logfiles['timestamp.c'])
env.Append(ESF_timestamp = timestampStatic)

Alias('timestamp', timestampStatic)
