# applications/systracePEP/systracePEP/SConscript
import os, sys
Import('env','curBaseDir')

if env['PEFCONFIG']['systracePEP'] == True:
	systracePEP=env.Program('systracePEP.c', LIBS=env['LIBS']+['logger','kvm',
															   'str_utils', 
															   'list_of_events', 'syscallHandler', 'data_flow_monitor', 'qfdtConnector','dataCont',
															   'systrace_utils','openbsd_utils','socket_utils',
															   'pdp',
															   'soup-2.4','soup_utils'])
	Depends(systracePEP, ['logger','utilities','datacont','syscallHandler','list_of_events'])
	Alias('systracePEP', [systracePEP])
else:
	print "Skipping systracePEP"
	Alias('systracePEP', [])




